export interface YouTubeSearchItem {
  id: {
    kind: string;
    channelId: string;
  };
  snippet: {
    channelId: string;
    title: string;
    description: string;
    thumbnails: {
      default: { url: string };
      medium: { url: string };
      high: { url: string };
    };
    channelTitle: string;
  };
}

export interface YouTubeSearchResponse {
  items?: YouTubeSearchItem[];
  error?: {
    code: number;
    message: string;
  };
}

export interface YouTubeChannelItem {
  id: string;
  snippet: {
    title: string;
    description: string;
    customUrl?: string;
    thumbnails: {
      default: { url: string };
      medium: { url: string };
      high: { url: string };
    };
  };
  statistics: {
    viewCount: string;
    subscriberCount: string;
    hiddenSubscriberCount: boolean;
    videoCount: string;
  };
  brandingSettings?: {
    channel?: {
      country?: string;
    };
  };
}

export interface YouTubeChannelResponse {
  items?: YouTubeChannelItem[];
  error?: {
    code: number;
    message: string;
  };
}

export interface NormalizedCreator {
  id: string; // will be uuid generated by us or DB later, we can omit or just use channel_id as temporary
  platform: 'youtube' | 'twitch' | 'kick';
  channel_id: string;
  slug: string;
  display_name: string;
  subscribers: number;
  verified: boolean;
  avatar_url?: string;
}

export interface YouTubePlaylistItem {
  snippet: {
    resourceId: {
      videoId: string;
    };
  };
}

export interface YouTubePlaylistItemsResponse {
  items?: YouTubePlaylistItem[];
  error?: {
    code: number;
    message: string;
  };
}

export interface YouTubeVideoItem {
  id: string;
  snippet: {
    publishedAt: string;
    title: string;
    description: string;
    thumbnails: {
      default: { url: string };
      medium: { url: string };
      high: { url: string };
    };
  };
  statistics: {
    viewCount: string;
    likeCount: string;
    commentCount: string;
  };
}

export interface YouTubeVideosResponse {
  items?: YouTubeVideoItem[];
  error?: {
    code: number;
    message: string;
  };
}

export interface NormalizedVideo {
  id: string;
  title: string;
  published_at: string;
  thumbnail_url: string;
  views: number;
  likes: number;
  comments: number;
  is_long?: boolean;
  live_broadcast_content?: string;
  duration_seconds?: number;
}

export interface CreatorAnalyticsData {
  profile: NormalizedCreator;
  metrics: {
    total_views: number;
    total_videos: number;
  };
  recent_videos: NormalizedVideo[];
}
