export interface YouTubeSearchItem {
  id: {
    kind: string;
    channelId: string;
  };
  snippet: {
    channelId: string;
    title: string;
    description: string;
    thumbnails: {
      default: { url: string };
      medium: { url: string };
      high: { url: string };
    };
    channelTitle: string;
  };
}

export interface YouTubeSearchResponse {
  items?: YouTubeSearchItem[];
  error?: {
    code: number;
    message: string;
  };
}

export interface YouTubeChannelItem {
  id: string;
  snippet: {
    title: string;
    description: string;
    customUrl?: string;
    thumbnails: {
      default: { url: string };
      medium: { url: string };
      high: { url: string };
    };
  };
  statistics: {
    viewCount: string;
    subscriberCount: string;
    hiddenSubscriberCount: boolean;
    videoCount: string;
  };
  brandingSettings?: {
    channel?: {
      country?: string;
    };
  };
}

export interface YouTubeChannelResponse {
  items?: YouTubeChannelItem[];
  error?: {
    code: number;
    message: string;
  };
}

export interface NormalizedCreator {
  id: string; // will be uuid generated by us or DB later, we can omit or just use channel_id as temporary
  platform: 'youtube' | 'twitch' | 'kick';
  channel_id: string;
  slug: string;
  display_name: string;
  subscribers: number;
  verified: boolean;
  avatar_url?: string;
}
